'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function ReportDownloadButton({ test, attempt, analysis }) {
    const [isGenerating, setIsGenerating] = useState(false);

    const generatePDF = async () => {
        setIsGenerating(true);
        try {
            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();

            // Header
            doc.setFontSize(22);
            doc.setTextColor(40, 44, 52);
            doc.text('Mindora - Performance Report', pageWidth / 2, 20, { align: 'center' });

            doc.setDrawColor(200, 200, 200);
            doc.line(20, 25, pageWidth - 20, 25);

            // Test Info
            doc.setFontSize(16);
            doc.text(test.title, 20, 40);
            
            doc.setFontSize(12);
            doc.setTextColor(100, 100, 100);
            doc.text(`Attempted on: ${new Date(attempt.startedAt).toLocaleDateString()}`, 20, 50);
            doc.text(`Status: ${attempt.status.toUpperCase()}`, 20, 57);

            // Summary Stats
            doc.setDrawColor(240, 240, 240);
            doc.setFillColor(248, 249, 250);
            doc.rect(20, 65, pageWidth - 40, 30, 'F');
            
            doc.setTextColor(40, 44, 52);
            doc.setFontSize(10);
            doc.text('SCORE', 30, 75);
            doc.text('ACCURACY', 80, 75);
            doc.text('TIME TAKEN', 130, 75);

            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text(`${attempt.score} / ${analysis.length}`, 30, 85);
            doc.text(`${Math.round((attempt.score / analysis.length) * 100)}%`, 80, 85);
            doc.text(`${Math.floor(attempt.timeSpentSeconds / 60)}m ${attempt.timeSpentSeconds % 60}s`, 130, 85);

            // Question Analysis Table
            const tableData = analysis.map((q, index) => [
                index + 1,
                q.text.substring(0, 80) + (q.text.length > 80 ? '...' : ''),
                q.isSkipped ? 'Skipped' : (q.isCorrect ? 'Correct' : 'Incorrect'),
                q.userAnswer || '-',
                q.correctAnswer || '-'
            ]);

            autoTable(doc, {
                startY: 105,
                head: [['#', 'Question', 'Result', 'Your Answer', 'Correct Answer']],
                body: tableData,
                headStyles: { fillColor: [79, 70, 229], textColor: 255 },
                alternateRowStyles: { fillColor: [250, 250, 255] },
                margin: { top: 105 },
                styles: { fontSize: 9 },
                columnStyles: {
                    0: { cellWidth: 10 },
                    1: { cellWidth: 70 },
                    2: { cellWidth: 20 },
                    3: { cellWidth: 40 },
                    4: { cellWidth: 40 }
                }
            });

            // Footer
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(10);
                doc.setTextColor(150, 150, 150);
                doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
                doc.text('Generated by Mindora AI Learning Platform', 20, doc.internal.pageSize.getHeight() - 10);
            }

            doc.save(`${test.title.replace(/\s+/g, '_')}_Report.pdf`);
        } catch (error) {
            console.error('Error generating PDF:', error);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <Button onClick={generatePDF} disabled={isGenerating} className="gap-2">
            {isGenerating ? (
                <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Generating...
                </>
            ) : (
                <>
                    <Download className="w-4 h-4" />
                    Download Report
                </>
            )}
        </Button>
    );
}
